baseurl = "/"
languageCode = "en-us"
title = "Growth Marketing Stack - How It Works"
copyright = "(c) 2022 dubarnstokr"
description = "How to implement growth marketing stack"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    languageLang = "en"
    weight = 1
    contentDir = "content"

googleAnalytics = "G-Z1VF7Q4YJT"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[Permalinks]
  post = "post/:slug"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true


# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/dubarnstokr2/website-hugo"
  weight = 10
