baseurl = "/"
languageCode = "en-us"
title = "Growth Marketing Stack - How It Works"
theme = "hugo-theme-basic"
copyright = "(c) 2022 dubarnstokr"
description = "How to implement growth marketing stack"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[Params]
  description = "How to implement growth marketing stack"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    languageLang = "en"
    weight = 1
  [languages.ru]
    languageName = "Russian"
    languageCode = "ru-ru"
    languageLang = "ru"
    weight = 2

googleAnalytics = "G-Z1VF7Q4YJT"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  twitter = "mksimiliano"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "post series"
  url = "series/"
  

[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true