title = "[Dev] Growth Marketing Stack - How It Works"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', 'CONTEXT']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
